### ISSUE TITLE
Restore the workspace all-target gate after worktree freshness output change

### ISSUE THREAD

**Issue by chubes4** [Extra-Chill/homeboy#13982]
## Problem

`cargo check --workspace --all-targets` fails on current `main` because the test helper constructing `WorktreeCreateOutput` in `crates/homeboy-cli/src/commands/worktree.rs` was not updated when PR #13962 added the required `handoff_freshness` field.

```text
error[E0063]: missing field `handoff_freshness` in initializer of `WorktreeCreateOutput`
  --> crates/homeboy-cli/src/commands/worktree.rs:844:9
```

## Acceptance criteria

- [ ] Every `WorktreeCreateOutput` fixture initializes `handoff_freshness` with semantically correct evidence or `None`.
- [ ] `cargo check --workspace --all-targets` passes from current `main`.
- [ ] The freshness behavior tests from #13940 remain green.

Introduced by #13962. Discovered while running the required gate for #13975.

---

AI assistance: OpenAI GPT-5.6 Sol via OpenCode reproduced the current-main compile failure, traced the field introduction to #13962, and drafted this tracker; Chris Huber directed the investigation.

**Comment by chubes4** [comment]
Fixed by `40b8a0e39` (#13984). The fixture sets `handoff_freshness: None` (`worktree.rs:765`) and the workspace all-target gate is restored.
---
*AI assistance disclosure: this triage was performed by Claude (Anthropic) running in OpenCode, driven by Chris Huber. The model cross-referenced the open-issue set against `origin/main` git history and current source, and every fix claim above was verified against a named commit or a `file:line` in the tree before this issue was closed.*
