### ISSUE TITLE
Regression: keep automatic Lab offload output compact and non-duplicative

### ISSUE THREAD

**Issue by chubes4** [Extra-Chill/homeboy#10455]
## Problem

Automatic Lab offload for `fuzz run` emits a large, duplicated transport/debug transcript instead of a compact operator result. One failed campaign printed:

- resource-policy prose
- runner connection and binary prose
- two separate rig discovery/install handoff blocks
- the full remote command and full controller/remapped/final argv provenance
- workspace cleanup prose
- raw Node stack trace
- the complete remote `homeboy/command-result/v3` fuzz envelope
- another Lab failure summary containing the same command and failure

The remote stdout itself was retained as about 9 KB and then embedded again in runner events and `runs show`. The output exceeded normal tool context and required manual searching to find the one actionable fact: `Cannot find module 'tar'`.

This is a regression of the compact-output behavior completed in #7476 and #9631, now through automatic capability offload rather than direct `runner exec`.

## Reproduction

```sh
homeboy --runner homeboy-lab fuzz run studio \
  --rig studio-db-dropin-fuzz \
  --profile pr-4356 \
  --path /Users/chubes/Developer/studio@fix-3518-import-db-dropin \
  --run-id studio-pr-4356-homeboy-v3 \
  --tracker-ref github-pr:Automattic/studio#4356 \
  --gate-profile strict
```

Runner job: `92118d3e-2b67-4dd1-9976-3aacc2786045`

## Expected contract

Default terminal output answers:

- where it ran
- whether staging and execution succeeded
- run/job identity
- one root-cause summary
- one status/evidence command

Full argv provenance, event streams, snapshots, telemetry, and nested command envelopes remain available via `--output`, `runs show --full`, `runner job logs`, or artifacts.

## Acceptance criteria

- Default automatic Lab offload output is bounded and prints remote stdout/stderr once.
- Nested Homeboy command-result JSON is parsed into the parent result rather than dumped and duplicated.
- Child rig discovery/install handoffs collapse into one parent staging summary.
- Failure output leads with the classified root cause and relevant phase.
- Full transport provenance remains retrievable but is not emitted by default.
- Add output-size and duplication tests for success, workspace setup failure, and fuzz workload failure.
- Cover direct `runner exec`, automatic capability offload, and structured `--output` independently.

## Related

- #7476 added compact runner execution output.
- #9631 fixed `runner exec --raw` printing full structured envelopes.
- This issue covers the same regression through automatic Lab capability offload.

## AI assistance

- Model: OpenAI GPT-5.6 Sol
- Tool: OpenCode
- Used for: Captured the full Lab fuzz transcript and durable events, isolated duplicated presentation layers, searched existing issues, and drafted this regression report under Chris Huber's direction.

**Comment by chubes4** [comment]
Reopening with a recurrence through `agent-task fanout cook-batch` on `homeboy 0.321.0+192964f61a7e`.

Executing two Lab cooks printed, for each child:

- connection and binary-version prose multiple times;
- the complete inline serialized agent-task plan;
- full `source_args`;
- full `remapped_args`;
- full `final_argv`;
- deeply nested provider instructions and metadata;
- complete handoff, telemetry, cleanup, and final batch envelopes.

The duplicated transport/provenance output dominated the result and obscured the actionable terminal fact: both providers succeeded and both Cooks stopped at promotion-response validation. The default output was large enough that operator review depended on searching the structured transcript rather than reading one compact batch summary.

Fanout: `cook-batch-wp-codebox-issue-2143-2-7c33c1b1676d`

Expected default output remains one line per child with runner, provider result, promotion/gate/finalization state, run id, and exact next action. Full plans and argv provenance belong behind `--full`, logs, artifacts, or `--output`. Please add batch-cook automatic Lab offload to the regression matrix.

AI assistance: OpenAI GPT-5.6 Sol via OpenCode captured the batch transcript, compared it with this tracker, and drafted the recurrence under Chris Huber's direction.

**Comment by chubes4** [comment]
Fresh recurrence through a single explicitly pinned Lab Cook. Default output embedded the complete serialized agent-task plan, provider instructions, local absolute paths, `source_args`, `remapped_args`, and `final_argv` twice across two infrastructure attempts. The actionable result was only that both attempts cancelled before provider start with `missing_runner_pid`. The transcript dominated tool context and made raw status search necessary. Cook: `agent-task-6cb53598-f2e7-4fa9-8b02-3f0090a64c40`.

AI assistance: OpenAI `gpt-5.6-sol` via OpenCode captured the Lab Cook transcript, isolated duplicated presentation layers, matched the recurrence to this tracker, and drafted the comment. Chris Huber reviewed and owns it.
