### ISSUE TITLE
origin/main test targets do not compile, so agents cannot distinguish their own breakage from a broken baseline

### ISSUE THREAD

**Issue by chubes4** [Extra-Chill/homeboy#13646]
## Problem

`origin/main` currently fails to compile its own test targets:

```
$ cargo check -p homeboy-cli --tests
error[E0425]: cannot find function `test_external_check_detail_resolver_fixture`
              in module `homeboy_cli::commands::ci`
 --> crates/homeboy-cli/tests/external_check_detail_resolver_fixture.rs:3:32
error: could not compile `homeboy-cli` (test "external_check_detail_resolver_fixture")
```

This is a test feature-gating defect, not caused by any candidate change. But a dispatched agent has no way to know that. It runs verification, sees a compile error, and cannot distinguish "my change broke this" from "this was already broken".

The failure modes are both bad: the agent burns attempts chasing a defect it did not cause, or it concludes the tree is broken and abandons correct work. I had to detect this myself and explicitly instruct every agent to ignore it — which also means agents are now instructed to skip a real verification surface.

## Related

The same run surfaced two tests in `homeboy-agents` that fail under parallel load and pass in isolation (`shared_evaluator_uses_effective_config_redacts_runtime_reason_and_deduplicates`, `provider_empty_stdout_captures_bounded_stderr_and_exit_context`). One agent independently confirmed the flake reproduces without its change. Flaky-under-parallelism tests have the same effect: they cost attempts and erode trust in the gate.

## Expected

Two things. Keep the default branch's test targets compiling — a broken baseline poisons every concurrent cook at once. And give agents a known-good baseline signal, so a gate failure that also fails on the merge-base is reported as pre-existing rather than attributed to the candidate.

---

*Filed with AI assistance: Claude Sonnet 4.5 via opencode. Compile failure reproduced on a clean worktree at origin/main with no local modifications.*
