### ISSUE TITLE
intra_method_duplicate Adjacent autofix can delete arguments, shipping compile-broken code

### ISSUE THREAD

**Issue by chubes4** [Extra-Chill/homeboy#1164]
## Summary

The `intra_method_duplicate` audit rule with relation `Adjacent` is classified `auto_apply=true`, so `refactor --write --only intramethodduplicate` (and the CI autofix path) will apply its edits unattended. But the fixer can collapse two "structurally identical" function **call sites** that differ in argument COUNT — deleting positional arguments — which produces compile errors.

Observed live on two consecutive CI autofix runs against Extra-Chill/homeboy#1160:
- `fc21651` — autofix deleted 6 of 7 positional args from one `make_fingerprint(...)` call. Build failed with E0061.
- `fe9efe3` — same PR, different autofix run, **same bug, same file, same call site**. Bot re-applied the same broken fix after the revert, even after #1161 merged. Build failed with E0061 again.

This is exactly the class of failure #1159 flagged as out of scope for #1161:

> "`homeboy refactor homeboy --from all --write --force` claims `audit: applied=true fixes_applied=44, files_modified=20` but produces a tree that does **not compile** (21 errors, e.g. `cannot find function test_file_path` after `pub fn → pub(crate) fn` narrowing in `scaffold/test.rs`). The autofix is willing to ship broken code in some configurations."

#1159 is closed, but that **second failure mode** — the fixer producing code that doesn't compile — is still present. This issue tracks it on its own terms.

## Reproduction

The minimal seed was already in `src/core/code_audit/impact.rs`, in the test module:

```rust
#[test]
fn test_diff_fingerprints_detects_removed_hook() {
    let base = make_fingerprint(
        "Foo.php",
        vec![], vec![], vec![],
        None, None,
        vec![("action", "my_custom_action")],
    );
    let current = make_fingerprint(
        "Foo.php",
        vec![], vec![], vec![],
        None, None,
        vec![("action", "my_renamed_action")],
    );
    // ...
}
```

Running the audit → refactor pipeline on this against a repo where it's flagged:

```bash
homeboy refactor homeboy --from audit --only intramethodduplicate --write --force
```

…produced (across two independent CI runs):

```rust
let current = make_fingerprint(vec![("action", "my_renamed_action")]);
// E0061: this function takes 7 arguments but 1 argument was supplied
```

The fixer saw two adjacent `make_fingerprint(...)` calls, noticed the argument **lists** were structurally similar (both `Vec<_>` at position 6, both literal), and collapsed the second call to the "minimal different prefix" — which happens to be arg count 1 instead of 7. Total information loss.

## Why it's dangerous

The rule has three relation modes, per MEMORY notes from #1159 investigation:

- **`Adjacent`** → auto-apply (this bug)
- **`SameIndentSmallGap`** → auto-apply
- **`SameIndentLargeGap`** → manual_only
- **`CrossBranch`** → manual_only

The `Adjacent` classification assumes that two near-identical adjacent expressions are safe to collapse, but that assumption breaks when:

1. The two calls pass different argument **counts** (as here — the bot picked the 1-arg shape)
2. The two calls pass different argument **types** where both happen to be valid syntactically
3. One call has a side-effecting expression the other does not

None of these are currently gated.

## Impact

Every PR in a component with even one `intra_method_duplicate Adjacent` finding in code it touches can hit this loop:

1. PR opens → Auto-refactor stage runs
2. Bot applies "fix" that breaks compile
3. Bot pushes break to PR branch
4. CI re-runs on broken code → Build/Lint fail → PR red
5. Contributor reverts the bot commit → bot re-applies on next push
6. Admin-merge or loop-breaking workaround required

This is essentially the #1159 deadlock but with worse consequences — the autofix doesn't just fail CI, it ships broken code that a downstream merge would propagate.

#1159 + #1161 fixed the dry-run/`--write` contract so the CI gate exits 0 when ALL collected edits are manual-only-declined. This issue is orthogonal: even when the fix IS auto-applicable, it shouldn't be auto-applied if the result doesn't compile.

## Suggested fixes

Pick one or any combination — they stack:

### 1. Post-fix `cargo check` gate (language-agnostic: run the component's build verify)

Simplest, strongest guarantee. After `apply_fix_policy(write=true)` writes edits to the working tree, run the component's "verify builds" command before committing. If it fails, revert the working tree and mark those fixes as declined with a structured error.

Pseudocode in `core/refactor/plan/sources.rs` or wherever the write commits:

```rust
let changed_files = apply_fix_policy(fixes, write: true);
if !changed_files.is_empty() {
    match run_build_verify(&component) {
        Ok(_) => { /* commit as now */ }
        Err(build_err) => {
            revert_working_tree(&changed_files);
            emit_declined(fixes, reason: "post-fix build verify failed", build_err);
        }
    }
}
```

Verify command comes from extension manifest — Rust extension would run `cargo check`, WordPress extension runs `composer --dry-run` or similar. Already a hook point most extensions have for `verify`/`lint`.

### 2. Narrower `Adjacent` safety rails on `intra_method_duplicate`

Before applying an `Adjacent` collapse, validate:

- **Argument-count equality** — don't collapse calls with different argument counts. The "longer-form → shorter-form" rewrite is never safe without semantic analysis.
- **Argument-type equality at positions retained** — if we're keeping arg N, it must be the same TYPE in both expressions (same AST shape, or same inferred type if available from sibling engine data).
- **Expression purity** — if either candidate call contains an obvious side-effect (mutation, `.unwrap()`, `?`, `await`, a method call on a non-pure type), downgrade to manual_only.

Even (a) alone would have blocked the two failures on #1160.

### 3. Downgrade all `intra_method_duplicate` variants to manual_only by default, with opt-in

Arguably the cleanest signal — this is a finding worth surfacing, but "collapse" is a semantic refactor with risks. Make it manual_only unconditionally; let users opt in per-component (`homeboy.json` autofix allowlist) if they trust their particular shape of duplicates.

This is what I did by hand to close out #1160 — extracted a helper function (`fingerprint_with_hook`) that captured the shared call shape, which is the audit's own suggested resolution. It just wasn't possible to **automate** safely.

## Testing

Whatever fix is chosen, a regression test should lock in the contract:

```rust
#[test]
fn adjacent_intra_method_duplicate_with_different_arg_counts_is_not_auto_apply() {
    // Two "adjacent" calls: make_fingerprint(7 args) and make_fingerprint(1 arg)
    // Fixer must either:
    //   - classify the fix as manual_only, or
    //   - produce an edit whose post-fix build succeeds, or
    //   - roll back on post-fix build failure
    // It must NOT commit a compile-breaking edit to disk.
}
```

## Context

This is the second failure mode called out in #1159's description. That issue's PR (#1161) fixed the dry-run/`--write` accounting mismatch and made the CI gate sound. This issue tracks the remaining concern: **when the gate correctly reports "write mode modified N files," those N file changes may still be broken**. The gate says the right thing; the fix itself is unsafe.

Both #1160 (merged, b46255e) and ext#212 (merged, 96c80d6) landed despite this bug because I manually extracted the helper. But contributors without write access or familiarity with the repo's test shapes would hit a hard wall.

## Related

- #1159 (closed by #1161) — dry-run/write contract mismatch
- #1158, #1156, #1149 — other homeboy-action / audit UX issues
