### ISSUE TITLE
fix(agents): workspace does not compile — ControlPlaneBlocker initializer missing state/reason/retry (regression from #14492)

### ISSUE THREAD

**Issue by chubes4** [Extra-Chill/homeboy#14501]
#14492 (`144f3bf9f`) added a `pre_execution_failure` blocker initializer in `crates/homeboy-agents/src/orchestration.rs:3905` that only sets `code` and `message`. `ControlPlaneBlocker` (`homeboy-control-plane-contract/src/resource.rs:659`) also requires `state`, `reason`, and `retry`, so every `cargo build/test` touching `homeboy-agents` fails:

```
error[E0063]: missing fields `reason`, `retry` and `state` in initializer of `ControlPlaneBlocker`
   --> crates/homeboy-agents/src/orchestration.rs:3905:25
```

This blocks any test run on main (including release-gate verification) regardless of the change under test. Fix is the obvious one: complete the initializer with `state: None, reason: None, retry: None`, matching the sibling `controller_failure` initializer at :3891.

Fixed in-branch on fix/14449-release-test-secret-env-projections (commit 2a916ce2f) and included in PR for #14449.
