### ISSUE TITLE
fix(agents): restore Windows compile after artifact root check

### ISSUE THREAD

**Issue by chubes4** [Extra-Chill/homeboy#11660]
## Problem

Current main fails the Windows workspace compile.

## Root cause

ArtifactRootGuard::verify() declares res under #[cfg(unix)] but evaluates if res on every platform. Windows therefore fails with E0425: cannot find value res in this scope.

Introduced by efa5e610f (fix(ci): restore Rust 1.95 warning-clean gate (#11652)).

## Evidence

- PR #11590 CI: https://github.com/Extra-Chill/homeboy/actions/runs/31055895700/job/92473197627
- Failing source: crates/homeboy-agents/src/agent_task_provider/artifact_finalization.rs:109-113
- Reproduce: cargo check --workspace --locked on Windows.

## Acceptance

- Keep the Unix device/inode check Unix-only.
- Preserve the existing Windows volume/file-ID check.
- Restore cargo check --workspace --locked on Windows.

## AI assistance

OpenAI openai/gpt-5.6-terra via OpenCode inspected the CI log, traced the compile error to the current base commit, and drafted this issue. Chris Huber reviewed and owns the work.
